dist: trusty
sudo: false
language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - xorg-dev
        - python3
        - python3-pip
        - libglu1-mesa-dev
        - libsuitesparse-dev
    env:
    - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7 && CONFIG=Debug"
  - os: osx
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install suite-sparse; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
- pip3 install --user sympy
- eval "${MATRIX_EVAL}"

script:
- cd cpp
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=$CONFIG ..
- make -j2
- make test
